### ISSUE TITLE
How to use this repo? Package it as a library?

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Commons#11]
It seems like this code is used as a starting point for the other apps (ie, copied over). But that means if you make a change here, you also need to make the change in every other *Simple* app.

Would it make sense to make this a library that provides the SimpleActivity, AboutActivity, etc classes? Then instead of extending AppCompatActivity in each app, extend the activities this package provides.

---

The reason I came here is that I started working on a patch for https://github.com/SimpleMobileTools/Simple-Notes/issues/35, and noticed that you're using an activity with a custom layout instead of loading preferences from xml. I was going to also make a patch to change that, but then I wasn't sure how I should do that so it would be reusable for all the Simple apps.

**Comment by tibbi** [comment]
thats exactly the goal of it, it is already a library. I want to remove as much translation/code/resource duplication as possible. So far its used only by the gallery, you can check it out. Im currently rewriting the calendar, then all the remaining apps will be using it too. Ill be off for a couple days now, but an updated calendar will be hopefully published within a couple days after I come back.
