### ISSUE TITLE
Config as a singleton

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Commons#12]
You can make config a singleton by changing it from a class to an object. Then just call it as `Config.METHOD` (instead of `config.METHOD`).

I know some people view singletons as an anti-pattern, but it seems like config is already a global state so there's no harm in it.

Edit: this would probably be done at the app level, not the library level; in retrospect I should have made this issue on the simple commons repo.

**Comment by tibbi** [comment]
not sure what you mean, any link to more details or sth?

**Comment by XyLoNaMiyX** [comment]
The problem if they used a static `Config` it would probably involve a static `Context` too — and in Android, static `Context` means memory leak, because `Context` objects are managed on the `Activity` lifecycle and should be destroyed too. Android Studio usually warns you about this.

**Comment by smichel17** [comment]
The way you do it is by subclassing Application, which there's only ever one instance of and stays running for the entire app lifecycle anyway. Here's an example:

The config is here. It refers to the application context on line 16: https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/java/nl/mpcjanssen/simpletask/util/Config.kt

And the application is here. Lines 62 and 247 are the relevant ones. https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/java/nl/mpcjanssen/simpletask/TodoApplication.kt

**Comment by XyLoNaMiyX** [comment]
> The way you get around that is by subclassing Application

I've came accross that solution a few times… But I don't think it's worth the trouble really.

**Comment by smichel17** [comment]
It's nice if you ever want to access config in a place that wouldn't normally have easy access to a context. Sure, you can pass around a context (or a config object), but it's nice to be able to call `Config.preference` and get the value of that preference, from anywhere. And the normal downside (introducing a global state) isn't really that big of a deal, since config is a global state anyway.

It's not that big of a deal. It's also not that much trouble. I just wanted to bring it up. @tibbi feel free to close this issue if you're not interested.

**Comment by tibbi** [comment]
okay thanks for the info, but I dont think its worth the time

**Comment by tibbi** [comment]
ive made Config an extension variable to save some space, at https://github.com/SimpleMobileTools/Simple-Commons/commit/1fa63a4ce3b1038e4be9a0b9f71361ff6c66561a
