### ISSUE TITLE
long Russian words

### ISSUE THREAD

**Issue by mcbaze** [SimpleMobileTools/Simple-Commons#17]
As i expected, some strings are too long to be displayed right. Here is settings screen from Simple Calendar
![screenshot_2017-01-11-01-26-37](https://cloud.githubusercontent.com/assets/8080391/21828704/064f0ae2-d7a3-11e6-9d09-709924e4077d.png)
There are overlapping parameter name and the value.
I think it is common problem, not this app only. Maybe it is the way to show only fixed number of characters if string is longer than N symbols?
I have just figured out that Kotlin has "ellipsize" property of textview. But i really don't know if it is possible to use this property with some layouts (like: res/layout/activity_settings.xml)

**Comment by tibbi** [comment]
there is ellipsize no matter if you use kotlin or not. I dont want to use it tho as it hides the strings end. What Ive made is that the left string will occupy 2 lines if necessary, so its still fully readable. Applied it to the calendar, and adding it to the gallery now. Ill leave the issue opened as a reminder for the other apps, once I get to them.

**Comment by tibbi** [comment]
those elements have been replaced in the gallery and calendar, remaining apps will sooner or later be fixed too.
