### ISSUE TITLE
Primary color in "last open apps" always default

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Commons#20]
Primary color set to black:
![screenshot_2017-01-17-18-32-48](https://cloud.githubusercontent.com/assets/22525368/22032153/804a59ce-dce3-11e6-86d0-4d50c8d11299.png)
![screenshot_2017-01-17-18-32-39](https://cloud.githubusercontent.com/assets/22525368/22032152/804a17f2-dce3-11e6-9489-965ea2a6243f.png)

I dont know if this changable during runtime. A workaround might be to set this background to dark (like some other apps. firefox and signal). However this might not look so nice when using the default colors.

Maybe adjust the icon colors too.

**Comment by tibbi** [comment]
that cannot be changed during runtime indeed and I dont want to make it black, so its staying for now.
