### ISSUE TITLE
Add fourth color option

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Commons#24]
"Font color on primary color"
set Primary and font color to white and background color to black. You cannt see the white font and buttons now

**Comment by tibbi** [comment]
a black primary and font color is probably more real than white. Anyway, I will probably just stick to black/white text if the color underneath the text is primary for now, a fourth color could complicate it.

**Comment by tibbi** [comment]
moving to https://github.com/SimpleMobileTools/Simple-Commons/issues/24
