### ISSUE TITLE
Pre-made dark & OLED themes

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Commons#33]
Originally reported at https://github.com/SimpleMobileTools/Simple-Gallery/issues/169 by @Cormak:

---

Not everybody needs to customize their theme from scratch. Most people just want an option in the settings to switch to a dark theme and an OLED theme. It would also be helpful to make sure these pre-made themes work with all visual elements of the app, as some elements can be made illegible if you select the wrong color.

**Comment by tibbi** [comment]
moving to a more generic https://github.com/SimpleMobileTools/General-Discussion/issues/22
