### ISSUE TITLE
Use X instead of back arrow on theme customization screen

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Commons#58]
From the [Material Guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs):

> **Navigation**
> 
> The “X” used in a full-screen dialog differs from an up arrow, which indicates the view’s state is constantly being saved. For example, an up arrow used in Settings indicates all changes are committed immediately without explicit confirmation or cancel actions.

Since theme changes are discarded, we should use an X (or change it so the changes are saved, but I think it makes sense for them to be discarded).

**Comment by tibbi** [comment]
Thanks, it makes sense, Ill check it out.

**Comment by tibbi** [comment]
Ive added the X and left saving as a check instead of text, Google is breaking their own guidelines there once again. The change is in the latest Commons library so it will sooner or later be applied to all apps, but Ill close the issue now.
