### ISSUE TITLE
radiobuttons lag

### ISSUE THREAD

**Issue by mcbaze** [SimpleMobileTools/Simple-Commons#8]
when you select one button from the group of buttons, the previous one changes color like it is inactive, but circle continues to be filled with dot. expected behavior is: unselected radiobutton is empty circle with inactive color
the bug comes with Simple Gallery v2.1
p.s. hope it is the right repo

**Comment by tibbi** [comment]
ye its the right repo, but so far I could reproduce it only on a Samsung device which does everything differently, and couldnt fix it yet.

**Comment by tibbi** [comment]
moving to https://github.com/SimpleMobileTools/General-Discussion/issues/25
